version: '3'

services:
  neo4j:
    image: neo4j:3.5.17
    ports:
      - "7474:7474"
      - "7687:7687"
      - "5005:5005"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_jvm_additional=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_dbms_memory_heap_max__size=8G
      - NEO4J_dbms_memory_heap_initial__size=8G
      - NEO4J_apoc_export_file_enabled=true
    volumes:
      - ./procedure/target/procedure-1.0-SNAPSHOT.jar:/plugins/procedure-1.0-SNAPSHOT.jar
      - neo4j_data:/data
      - neo4j_import:/import
  web:
    build: .
    ports:
      - "7000:7000"
    environment:
      - JAR_FILE=client-1.0-SNAPSHOT.jar
    volumes:
    - ./tdbg-client/target/client-1.0-SNAPSHOT.jar:/usr/share/javalin/my-javalin.jar
    - ./docker.properties:/usr/share/javalin/client.properties
volumes:
  neo4j_data: {}
  neo4j_import: {}
